In [1]:
import json
import numpy as np

In [2]:
f=open('input(l1).json')
dimensions=json.load(f)

In [3]:
dimensions

{'die': {'width': 800, 'height': 600, 'rows': 1, 'columns': 5},
 'street_width': 0,
 'care_areas': [{'top_left': {'x': 0, 'y': 600},
   'bottom_right': {'x': 800, 'y': 0}}],
 'exclusion_zones': []}

In [4]:
type(dimensions)

dict

In [5]:
w=dimensions['die']['width']
h=dimensions['die']['height']
print(w,h)

800 600


In [6]:
care_areas=[]
for i in dimensions['care_areas']:
    care_areas.append(((i['top_left']['x'],i['top_left']['y']),(i['bottom_right']['x'],i['bottom_right']['y'])))
print(care_areas)

[((0, 600), (800, 0))]


In [7]:
import cv2

In [17]:
die1=cv2.imread('wafer_image_1(l1).png',cv2.IMREAD_GRAYSCALE)

In [18]:
print(die1)

[[255 255 255 ... 255 255 255]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 ...
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]]


In [19]:
die2=cv2.imread('wafer_image_2(l1).png',cv2.IMREAD_GRAYSCALE)
die3=cv2.imread('wafer_image_3(l1).png',cv2.IMREAD_GRAYSCALE)
die4=cv2.imread('wafer_image_4(l1).png',cv2.IMREAD_GRAYSCALE)
die5=cv2.imread('wafer_image_5(l1).png',cv2.IMREAD_GRAYSCALE)

In [20]:
np.unique(die1).shape

(48,)

In [30]:
wafer=np.stack([die1,die2,die3,die4,die5])

In [31]:
print(wafer)

[[[255 255 255 ... 255 255 255]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  ...
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]]

 [[255 255 255 ... 255 255 255]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  ...
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]]

 [[255 255 255 ... 255 255 255]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  ...
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]]

 [[255 255 255 ... 255 255 255]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  ...
  [128 128 128 ... 128 128 128]
  [128 128 159 ... 128 128 128]
  [128 128 128 ... 128 128 128]]

 [[255 255 255 ... 255 255 255]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  ...
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]
  [128 128 128 ... 128 128 128]]]


In [32]:
wafer.shape

(5, 600, 800)

In [36]:
print(wafer[0,0])

[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 173 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 159 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 133 255 255 255 255 255 255 255 255 255 255 25

In [28]:
np.unique(die1)

array([128, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 255], dtype=uint8)

This model will work under the condition that atleast one image will have the correct pixel for one pixel comparision. Compare the 